sudo: required

env:
  - DOCKER_COMPOSE_VERSION=1.22.0

services:
  - docker

branches:
  - master
  - development
  - /.*release.*/

language: python

python:
  - "3.6"

before_install:
  - pip install coveralls
  - sudo apt-get update
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version

install:
  - echo 'Iniciando script de instalação'
  - docker-compose up -d
  - echo 'Iniciando migração'
  - docker-compose exec web ./manage.py makemigrations
  - docker-compose exec web ./manage.py migrate


script:
  - docker-compose exec web coverage erase
  - docker-compose exec web coverage run --source='.' manage.py test
  - docker-compose exec web coverage report
  - docker-compose exec web flake8

after_script:
  - docker-compose down
 
after_sucess:
  - coveralls
