version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: ./wait-for-it.sh db:5432 -- bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db 
